import { describe, test, expect } from 'vitest'
import { createBotSession, getSnapshot, injectState, sendCmd, sendCmdRaw, deleteSession } from '../helpers/api'
import { buildPatch } from '../helpers/scenario'

// All trading tests manage sessions manually because the command sequence is
// inherently multi-step and stateful (tradeId is generated by the backend).

async function setup2Player(ownedBySeat0: string[], ownedBySeat1: string[], options: {
  seat0Cash?: number
  seat1Cash?: number
  seat0JailCards?: number
} = {}) {
  const sid = await createBotSession(2)
  const snap0 = await getSnapshot(sid)
  const patch = buildPatch({
    description: '', rules: [],
    players: [
      { cash: options.seat0Cash ?? 1500, boardIndex: 0, getOutOfJailCards: options.seat0JailCards ?? 0 },
      { cash: options.seat1Cash ?? 1500, boardIndex: 10 },
    ],
    ownedProperties: { 0: ownedBySeat0, 1: ownedBySeat1 },
    turn: { seat: 0, phase: 'WAITING_FOR_END_TURN' },
    expectedAfter: {},
  }, snap0)
  await injectState(sid, patch)
  return { sid, ids: snap0.state!.players.map(p => p.playerId) }
}

describe('Trading', () => {
  test('7.1 property ↔ property trade → ownerships swap', async () => {
    // seat0 offers B1, requests B2 from seat1
    const { sid, ids } = await setup2Player(['B1'], ['B2'])
    try {
      await sendCmd(sid, { type: 'OpenTrade', actorPlayerId: ids[0], recipientPlayerId: ids[1] })
      let snap = await getSnapshot(sid)
      const tradeId = snap.state!.tradeState!.tradeId
      // offer B1 (offeredSide=true = what seat0 gives)
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: true, propertyIdsToAdd: ['B1'] } })
      // request B2 (offeredSide=false = what seat0 requests)
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: false, propertyIdsToAdd: ['B2'] } })
      await sendCmd(sid, { type: 'SubmitTradeOffer', actorPlayerId: ids[0], tradeId })
      await sendCmd(sid, { type: 'AcceptTrade', actorPlayerId: ids[1], tradeId })
      snap = await getSnapshot(sid)
      const b1 = snap.state!.properties.find(p => p.propertyId === 'B1')!
      const b2 = snap.state!.properties.find(p => p.propertyId === 'B2')!
      expect(b1.ownerPlayerId).toBe(ids[1])  // seat1 now owns B1
      expect(b2.ownerPlayerId).toBe(ids[0])  // seat0 now owns B2
    } finally {
      await deleteSession(sid)
    }
  })

  test('7.2 property ↔ cash trade → ownership + cash change', async () => {
    // seat0 offers B1, requests €100 from seat1
    const { sid, ids } = await setup2Player(['B1'], [])
    try {
      await sendCmd(sid, { type: 'OpenTrade', actorPlayerId: ids[0], recipientPlayerId: ids[1] })
      let snap = await getSnapshot(sid)
      const tradeId = snap.state!.tradeState!.tradeId
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: true, propertyIdsToAdd: ['B1'] } })
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: false, replaceMoneyAmount: 100 } })
      await sendCmd(sid, { type: 'SubmitTradeOffer', actorPlayerId: ids[0], tradeId })
      await sendCmd(sid, { type: 'AcceptTrade', actorPlayerId: ids[1], tradeId })
      snap = await getSnapshot(sid)
      const b1 = snap.state!.properties.find(p => p.propertyId === 'B1')!
      expect(b1.ownerPlayerId).toBe(ids[1])    // seat1 gets B1
      expect(snap.state?.players[0].cash).toBe(1500 + 100)  // seat0 gets €100
      expect(snap.state?.players[1].cash).toBe(1500 - 100)  // seat1 pays €100
    } finally {
      await deleteSession(sid)
    }
  })

  test('7.3 GOOJF card included in trade → card transfers', async () => {
    // seat0 has 1 GOOJF card, offers it to seat1 for B2
    const { sid, ids } = await setup2Player([], ['B2'], { seat0JailCards: 1 })
    try {
      await sendCmd(sid, { type: 'OpenTrade', actorPlayerId: ids[0], recipientPlayerId: ids[1] })
      let snap = await getSnapshot(sid)
      const tradeId = snap.state!.tradeState!.tradeId
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: true, toggleJailCard: true } })
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: false, propertyIdsToAdd: ['B2'] } })
      await sendCmd(sid, { type: 'SubmitTradeOffer', actorPlayerId: ids[0], tradeId })
      await sendCmd(sid, { type: 'AcceptTrade', actorPlayerId: ids[1], tradeId })
      snap = await getSnapshot(sid)
      expect(snap.state?.players[0].getOutOfJailCards).toBe(0)  // seat0 gave away card
      expect(snap.state?.players[1].getOutOfJailCards).toBe(1)  // seat1 received card
    } finally {
      await deleteSession(sid)
    }
  })

  test('7.4 declining a trade closes it without changing ownership', async () => {
    // seat0 offers B1, seat1 declines → trade cancelled, B1 stays with seat0
    const { sid, ids } = await setup2Player(['B1'], ['B2'])
    try {
      await sendCmd(sid, { type: 'OpenTrade', actorPlayerId: ids[0], recipientPlayerId: ids[1] })
      let snap = await getSnapshot(sid)
      const tradeId = snap.state!.tradeState!.tradeId
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: true, propertyIdsToAdd: ['B1'] } })
      await sendCmd(sid, { type: 'SubmitTradeOffer', actorPlayerId: ids[0], tradeId })
      await sendCmd(sid, { type: 'DeclineTrade', actorPlayerId: ids[1], tradeId })
      snap = await getSnapshot(sid)
      expect(snap.state?.tradeState).toBeNull()           // trade closed
      const b1 = snap.state!.properties.find(p => p.propertyId === 'B1')!
      expect(b1.ownerPlayerId).toBe(ids[0])               // B1 still owned by seat0
    } finally {
      await deleteSession(sid)
    }
  })

  test('7.5 cannot trade property with buildings → rejected', async () => {
    // seat0 owns B1+B2 with houses. Can't trade B1 (has houses).
    const { sid, ids } = await setup2Player(['B1', 'B2'], [])
    try {
      // Inject houses on B1
      const snap0 = await getSnapshot(sid)
      const patch = buildPatch({
        description: '', rules: [],
        players: [{ cash: 1500, boardIndex: 0 }, { cash: 1500, boardIndex: 10 }],
        ownedProperties: { 0: ['B1', 'B2'] },
        propertyOverrides: { B1: { houseCount: 1 } },
        turn: { seat: 0, phase: 'WAITING_FOR_END_TURN' },
        expectedAfter: {},
      }, snap0)
      await injectState(sid, patch)

      await sendCmd(sid, { type: 'OpenTrade', actorPlayerId: ids[0], recipientPlayerId: ids[1] })
      let snap = await getSnapshot(sid)
      const tradeId = snap.state!.tradeState!.tradeId
      // Try to add B1 (has 1 house) to offer
      await sendCmd(sid, { type: 'EditTradeOffer', actorPlayerId: ids[0], tradeId, patch: { offeredSide: true, propertyIdsToAdd: ['B1'] } })
      // SubmitTradeOffer should be rejected because B1 has buildings
      const result = await sendCmdRaw(sid, { type: 'SubmitTradeOffer', actorPlayerId: ids[0], tradeId })
      expect(result.accepted).toBe(false)
      // B1 ownership unchanged
      snap = await getSnapshot(sid)
      const b1 = snap.state!.properties.find(p => p.propertyId === 'B1')!
      expect(b1.ownerPlayerId).toBe(ids[0])
    } finally {
      await deleteSession(sid)
    }
  })
})
